/**
 * GithubCommenter.ts — opt-in PR comment poster.
 *
 * Only runs when GITHUB_TOKEN + PGWEN_FIX_GH_PR + PGWEN_FIX_GH_REPO are all
 * set in the environment. Otherwise: silent no-op. Uses GitHub's REST API
 * over `fetch` (no new npm dependency); `@octokit/rest` could be wired in
 * later but the surface here is small enough that hand-rolled fetch keeps
 * the dependency graph clean and avoids the Nexus npm proxy install dance
 * for v1.
 *
 * Idempotency: comments embed a hidden HTML marker
 * (`<!-- pgwen-fix:auto -->`). On every run we list the PR's comments,
 * find the most recent one carrying the marker, and PATCH it instead of
 * POSTing a new one — so repeated CI runs never spam the PR.
 */

import type { Suggestion } from './types';

export const COMMENT_MARKER = '<!-- pgwen-fix:auto -->';

export interface GithubEnv {
  GITHUB_TOKEN?: string | undefined;
  PGWEN_FIX_GH_PR?: string | undefined;
  PGWEN_FIX_GH_REPO?: string | undefined;
  /** Override GitHub Enterprise API base. Default: https://api.github.com */
  GITHUB_API_URL?: string | undefined;
}

export interface PostCommentInputs {
  suggestions: Suggestion[];
  env: GithubEnv;
  /** Override `fetch` for tests. Defaults to global `fetch`. */
  fetchImpl?: typeof fetch;
}

export type PostCommentOutcome =
  | { kind: 'skipped'; reason: string }
  | { kind: 'created'; commentUrl: string }
  | { kind: 'updated'; commentUrl: string };

/**
 * Build the Markdown body that goes into the PR comment. Public so tests
 * can snapshot it without making a real API call.
 */
export function buildCommentBody(suggestions: Suggestion[]): string {
  const lines: string[] = [];
  lines.push(COMMENT_MARKER);
  lines.push('## pgwen-fix · suggested locator fixes');
  lines.push('');
  lines.push(`pgwen-fix detected **${suggestions.length}** suggestion${suggestions.length === 1 ? '' : 's'} from the latest run.`);
  lines.push('Each block below is a proposal — review and apply with \`patch -p1\` if accepted.');
  lines.push('');
  for (const s of suggestions) {
    lines.push(`### ${s.scenario_name}`);
    lines.push('');
    lines.push(`- **Step:** \`${s.step_text}\``);
    lines.push(`- **Binding:** \`${s.binding_name}\``);
    lines.push(`- **Location:** \`${s.file}:${s.line}\``);
    lines.push(`- **Confidence:** ${s.confidence}`);
    lines.push('');
    lines.push('```diff');
    // Trim trailing newline to keep the fenced block tight.
    lines.push(s.patch.replace(/\n+$/, ''));
    lines.push('```');
    lines.push('');
    lines.push(`<details><summary>Why</summary>${s.rationale.replace(/\n/g, ' ')}</details>`);
    lines.push('');
  }
  lines.push('_Generated by pgwen-fix in suggest-only mode — no commits or branches were created._');
  return lines.join('\n');
}

interface GithubComment {
  id: number;
  body: string;
  html_url: string;
}

/**
 * Post (or idempotently update) the suggestions comment on the configured PR.
 * Returns `{ kind: 'skipped' }` with a reason when the required env vars are
 * missing — never throws on configuration absence.
 */
export async function postPullRequestComment(inputs: PostCommentInputs): Promise<PostCommentOutcome> {
  const { env } = inputs;
  if (!env.GITHUB_TOKEN) return { kind: 'skipped', reason: 'GITHUB_TOKEN is not set' };
  if (!env.PGWEN_FIX_GH_PR) return { kind: 'skipped', reason: 'PGWEN_FIX_GH_PR is not set' };
  if (!env.PGWEN_FIX_GH_REPO) return { kind: 'skipped', reason: 'PGWEN_FIX_GH_REPO is not set' };
  if (inputs.suggestions.length === 0) return { kind: 'skipped', reason: 'no suggestions to post' };

  const apiBase = (env.GITHUB_API_URL ?? 'https://api.github.com').replace(/\/$/, '');
  const repo = env.PGWEN_FIX_GH_REPO;
  const prNumber = env.PGWEN_FIX_GH_PR;
  const fetchImpl = inputs.fetchImpl ?? fetch;
  const headers = {
    Authorization: `Bearer ${env.GITHUB_TOKEN}`,
    Accept: 'application/vnd.github+json',
    'Content-Type': 'application/json',
    'X-GitHub-Api-Version': '2022-11-28',
  } as const;

  const body = buildCommentBody(inputs.suggestions);

  // Step 1: locate a prior pgwen-fix comment by marker.
  const listUrl = `${apiBase}/repos/${repo}/issues/${prNumber}/comments?per_page=100`;
  const listRes = await fetchImpl(listUrl, { headers });
  if (!listRes.ok) {
    return { kind: 'skipped', reason: `GitHub list-comments returned ${listRes.status}` };
  }
  const existing = (await listRes.json()) as GithubComment[];
  const prior = [...existing].reverse().find((c) => c.body.includes(COMMENT_MARKER));

  if (prior) {
    const patchUrl = `${apiBase}/repos/${repo}/issues/comments/${prior.id}`;
    const patchRes = await fetchImpl(patchUrl, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({ body }),
    });
    if (!patchRes.ok) {
      return { kind: 'skipped', reason: `GitHub PATCH-comment returned ${patchRes.status}` };
    }
    const updated = (await patchRes.json()) as GithubComment;
    return { kind: 'updated', commentUrl: updated.html_url };
  }

  // Step 2: no prior — create.
  const createUrl = `${apiBase}/repos/${repo}/issues/${prNumber}/comments`;
  const createRes = await fetchImpl(createUrl, {
    method: 'POST',
    headers,
    body: JSON.stringify({ body }),
  });
  if (!createRes.ok) {
    return { kind: 'skipped', reason: `GitHub POST-comment returned ${createRes.status}` };
  }
  const created = (await createRes.json()) as GithubComment;
  return { kind: 'created', commentUrl: created.html_url };
}
