/**
 * ClaudeClient.ts — fetch-based Anthropic /v1/messages caller (Phase 5
 * of §16).
 *
 * Thin wrapper around Node 18+'s built-in `fetch`. No SDK dependency.
 * Sends a `PromptRequestBody` (from Phase 2's `buildPrompt`), parses
 * the tool_use response, returns a typed `ClaudeCallResult` carrying
 * the structured DiagnoseOutput and a token/cache usage breakdown.
 *
 * Retries:
 *   - 429 + 5xx are retried with exponential backoff + small jitter.
 *   - A Retry-After header (seconds or HTTP-date) is honoured when present.
 *   - 4xx other than 429 fails fast — those are caller bugs (bad key,
 *     bad request, etc.) and retrying just wastes budget.
 *
 * fetchImpl is injectable so tests never touch the network. The default
 * is the global `fetch`.
 */

import type { PromptRequestBody, ToolDefinition } from './Prompt';
import { REPORT_DIAGNOSIS_TOOL } from './Prompt';
import type { DiagnoseOutput } from './types';

// ─── Public types ──────────────────────────────────────────────────────────

export interface ClaudeClientOptions {
  apiKey: string;
  /** Default 'https://api.anthropic.com'. */
  baseUrl?: string;
  /**
   * Max retries on 429 + 5xx. Default 3. A retry attempt is in addition to
   * the initial request — so `maxRetries: 3` makes at most 4 HTTP calls.
   */
  maxRetries?: number;
  /** Base delay between retries in ms; backoff doubles each attempt. Default 1000. */
  retryBaseDelayMs?: number;
  /**
   * Inject a fetch implementation for tests. Defaults to the global `fetch`.
   * The type matches the lib.dom `fetch` signature so any Node-builtin /
   * undici / cross-fetch impl drops in.
   */
  fetchImpl?: typeof fetch;
  /**
   * Override / extend headers. Useful when an account requires a specific
   * `anthropic-beta` header that pgwen doesn't know about by default.
   */
  extraHeaders?: Record<string, string>;
  /**
   * Override the Anthropic API version header. Default '2023-06-01'.
   */
  anthropicVersion?: string;
  /** Inject a sleep fn (for tests). Defaults to setTimeout-based. */
  sleepImpl?: (ms: number) => Promise<void>;
}

export interface ClaudeCallUsage {
  inputTokens: number;
  outputTokens: number;
  /** Tokens served from prompt cache (charged at the cached rate). */
  cachedInputTokens: number;
  /** Tokens written to the prompt cache (charged at a premium one time). */
  cacheCreationTokens: number;
}

export interface ClaudeCallResult {
  output: DiagnoseOutput;
  usage: ClaudeCallUsage;
  /** The model the response was generated by. */
  model: string;
  /** Unique message id from Anthropic — useful for telemetry. */
  messageId: string;
}

export class ClaudeError extends Error {
  override readonly name = 'ClaudeError';
  constructor(
    message: string,
    readonly status?: number,
    readonly errorType?: string,
    readonly attempts?: number,
  ) {
    super(message);
  }
}

// ─── Internals — Anthropic API response shape (subset we use) ─────────────

interface ApiMessageResponse {
  id: string;
  type: 'message';
  role: 'assistant';
  model: string;
  content: ApiContentBlock[];
  stop_reason: string;
  usage: {
    input_tokens: number;
    output_tokens: number;
    cache_creation_input_tokens?: number;
    cache_read_input_tokens?: number;
  };
}

interface ApiToolUseBlock {
  type: 'tool_use';
  id: string;
  name: string;
  input: unknown;
}

interface ApiTextBlock {
  type: 'text';
  text: string;
}

type ApiContentBlock = ApiToolUseBlock | ApiTextBlock | { type: string };

interface ApiErrorEnvelope {
  type: 'error';
  error: { type: string; message: string };
}

// ─── Client ────────────────────────────────────────────────────────────────

export class ClaudeClient {
  private readonly apiKey: string;
  private readonly baseUrl: string;
  private readonly maxRetries: number;
  private readonly retryBaseDelayMs: number;
  private readonly fetchImpl: typeof fetch;
  private readonly extraHeaders: Record<string, string>;
  private readonly anthropicVersion: string;
  private readonly sleepImpl: (ms: number) => Promise<void>;

  constructor(opts: ClaudeClientOptions) {
    if (!opts.apiKey || typeof opts.apiKey !== 'string') {
      throw new ClaudeError('ClaudeClient requires a non-empty apiKey');
    }
    this.apiKey = opts.apiKey;
    this.baseUrl = (opts.baseUrl ?? 'https://api.anthropic.com').replace(/\/$/, '');
    this.maxRetries = opts.maxRetries ?? 3;
    this.retryBaseDelayMs = opts.retryBaseDelayMs ?? 1000;
    this.fetchImpl = opts.fetchImpl ?? fetch;
    this.extraHeaders = opts.extraHeaders ?? {};
    this.anthropicVersion = opts.anthropicVersion ?? '2023-06-01';
    this.sleepImpl = opts.sleepImpl ?? defaultSleep;
  }

  /**
   * POST a prompt to /v1/messages, retry transient failures, return the
   * structured tool_use payload as a DiagnoseOutput plus usage telemetry.
   */
  async call(body: PromptRequestBody): Promise<ClaudeCallResult> {
    const url = `${this.baseUrl}/v1/messages`;
    const headers: Record<string, string> = {
      'content-type': 'application/json',
      'x-api-key': this.apiKey,
      'anthropic-version': this.anthropicVersion,
      ...this.extraHeaders,
    };
    const init: RequestInit = {
      method: 'POST',
      headers,
      body: JSON.stringify(body),
    };

    let lastError: ClaudeError | undefined;
    for (let attempt = 0; attempt <= this.maxRetries; attempt++) {
      let response: Response;
      try {
        response = await this.fetchImpl(url, init);
      } catch (err) {
        // Network / DNS errors are retryable.
        lastError = new ClaudeError(
          `network error: ${err instanceof Error ? err.message : String(err)}`,
          undefined,
          'network_error',
        );
        if (attempt < this.maxRetries) {
          await this.sleepImpl(this.backoffMs(attempt));
          continue;
        }
        break;
      }

      if (response.ok) {
        const json = (await response.json()) as ApiMessageResponse;
        return parseSuccessResponse(json, body.tools);
      }

      // Non-OK: extract error info; decide retry vs. throw.
      const status = response.status;
      const errorInfo = await safeReadError(response);
      const retryable = status === 429 || (status >= 500 && status < 600);
      lastError = new ClaudeError(
        errorInfo.message || `HTTP ${status}`,
        status,
        errorInfo.errorType,
      );

      if (!retryable || attempt >= this.maxRetries) break;
      const retryAfter = parseRetryAfter(response.headers.get('retry-after'));
      await this.sleepImpl(retryAfter ?? this.backoffMs(attempt));
    }

    const attempts = this.maxRetries + 1;
    throw new ClaudeError(
      `Claude /v1/messages failed after ${attempts} attempt(s): ${lastError?.message ?? 'unknown error'}`,
      lastError?.status,
      lastError?.errorType,
      attempts,
    );
  }

  private backoffMs(attempt: number): number {
    // Exponential with small jitter to avoid retry storms across parallel runs.
    const base = this.retryBaseDelayMs * 2 ** attempt;
    const jitter = Math.floor(Math.random() * Math.min(250, base * 0.1));
    return base + jitter;
  }
}

// ─── Pure helpers (exported for direct tests) ──────────────────────────────

export function parseSuccessResponse(
  json: ApiMessageResponse,
  tools: ToolDefinition[],
): ClaudeCallResult {
  if (!json || json.type !== 'message' || !Array.isArray(json.content)) {
    throw new ClaudeError(
      `unexpected response shape from /v1/messages (no "message" envelope)`,
    );
  }

  const expectedToolName = tools[0]?.name ?? REPORT_DIAGNOSIS_TOOL;
  const toolBlock = json.content.find(
    (b): b is ApiToolUseBlock =>
      (b as ApiContentBlock).type === 'tool_use' &&
      (b as ApiToolUseBlock).name === expectedToolName,
  );

  if (!toolBlock) {
    throw new ClaudeError(
      `Claude did not call the expected tool "${expectedToolName}" — stop_reason was "${json.stop_reason}"`,
    );
  }

  // Only the diagnose tool returns a DiagnoseOutput. Other callers (e.g.
  // heal's `propose_locator`) supply their own tool + schema and validate
  // the payload themselves — ClaudeClient stays agnostic to their shape.
  if (expectedToolName === REPORT_DIAGNOSIS_TOOL && !isValidDiagnoseOutput(toolBlock.input)) {
    throw new ClaudeError(
      `tool_use payload is missing required DiagnoseOutput fields`,
    );
  }

  const usage = json.usage ?? { input_tokens: 0, output_tokens: 0 };
  return {
    output: toolBlock.input as DiagnoseOutput,
    usage: {
      inputTokens: usage.input_tokens ?? 0,
      outputTokens: usage.output_tokens ?? 0,
      cachedInputTokens: usage.cache_read_input_tokens ?? 0,
      cacheCreationTokens: usage.cache_creation_input_tokens ?? 0,
    },
    model: json.model,
    messageId: json.id,
  };
}

/**
 * Liberal shape check on Claude's tool input. We refuse obviously
 * malformed payloads (missing required top-level keys, wrong types
 * for the enums) but DO NOT reject every minor deviation — the
 * caller can still use a slightly-off output, and BudgetGate /
 * cache will record it. The patch applier enforces the §12 hard
 * rules (machine_proposal null unless locator_drift+high, etc.).
 */
function isValidDiagnoseOutput(input: unknown): input is DiagnoseOutput {
  if (!input || typeof input !== 'object') return false;
  const o = input as Record<string, unknown>;
  const required = [
    'category',
    'confidence',
    'human_explanation',
    'evidence',
    'alternatives_considered',
    'files_likely_involved',
    'escalation_signals',
    'machine_proposal',
    'auto_fix_safe',
  ];
  for (const key of required) {
    if (!(key in o)) return false;
  }
  if (typeof o['category'] !== 'string') return false;
  if (typeof o['confidence'] !== 'string') return false;
  if (typeof o['human_explanation'] !== 'string') return false;
  if (typeof o['auto_fix_safe'] !== 'boolean') return false;
  if (!Array.isArray(o['evidence'])) return false;
  if (!Array.isArray(o['alternatives_considered'])) return false;
  if (!Array.isArray(o['files_likely_involved'])) return false;
  return true;
}

async function safeReadError(
  response: Response,
): Promise<{ message: string; errorType?: string }> {
  try {
    const body = (await response.json()) as ApiErrorEnvelope | Record<string, unknown>;
    if (body && typeof body === 'object' && 'error' in body) {
      const envelope = body as ApiErrorEnvelope;
      return {
        message: envelope.error?.message ?? '',
        errorType: envelope.error?.type,
      };
    }
    return { message: JSON.stringify(body) };
  } catch {
    return { message: response.statusText };
  }
}

/** Parse a `Retry-After` value into milliseconds; returns undefined when absent or malformed. */
export function parseRetryAfter(value: string | null): number | undefined {
  if (!value) return undefined;
  const trimmed = value.trim();
  if (trimmed.length === 0) return undefined;
  // Integer seconds form.
  const asInt = Number(trimmed);
  if (Number.isFinite(asInt) && asInt >= 0) return Math.floor(asInt * 1000);
  // HTTP-date form.
  const asDate = Date.parse(trimmed);
  if (!Number.isNaN(asDate)) {
    const delta = asDate - Date.now();
    return delta > 0 ? delta : 0;
  }
  return undefined;
}

function defaultSleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
